name: kmeans-clustering-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy>=1.24.0
  - scikit-learn>=1.3.0
  - pip:
    - azureml-inference-server-http
    - inference-schema[numpy-support]
